/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forger;

import java.awt.Color;

/**
 *
 * @author samuelzun
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        jugar1 = new javax.swing.JButton();
        ayuda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(806, 600));
        setSize(800,600);

        fondo.setBackground(new java.awt.Color(0, 0, 0));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setBackground(new java.awt.Color(204, 204, 204));
        titulo.setFont(new java.awt.Font("Papyrus", 3, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 204, 153));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("FORGER");
        fondo.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, 800, 60));

        salir.setBackground(new java.awt.Color(84, 53, 22));
        salir.setFont(new java.awt.Font("Papyrus", 0, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(255, 204, 153));
        salir.setText("SALIR");
        salir.setToolTipText("");
        salir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 153), 1, true));
        salir.setOpaque(true);
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salirMouseExited(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        fondo.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 100, 30));

        jugar1.setBackground(new java.awt.Color(84, 53, 22));
        jugar1.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        jugar1.setForeground(new java.awt.Color(255, 204, 153));
        jugar1.setText("JUGAR");
        jugar1.setToolTipText("");
        jugar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 153), 1, true));
        jugar1.setOpaque(true);
        jugar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jugar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jugar1MouseExited(evt);
            }
        });
        jugar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugar1ActionPerformed(evt);
            }
        });
        fondo.add(jugar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 160, 50));

        ayuda.setBackground(new java.awt.Color(84, 53, 22));
        ayuda.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        ayuda.setForeground(new java.awt.Color(255, 204, 153));
        ayuda.setText("AYUDA");
        ayuda.setToolTipText("");
        ayuda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 153), 1, true));
        ayuda.setOpaque(true);
        ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ayudaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ayudaMouseExited(evt);
            }
        });
        ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaActionPerformed(evt);
            }
        });
        fondo.add(ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_salirActionPerformed

    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        // TODO add your handling code here:
        salir.setBackground(Color.decode("#8D5925"));
        
    }//GEN-LAST:event_salirMouseEntered

    private void salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseExited
        // TODO add your handling code here:
        salir.setBackground(Color.decode("#543516"));
        
    }//GEN-LAST:event_salirMouseExited

    private void ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ayudaActionPerformed

    private void ayudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayudaMouseEntered
        // TODO add your handling code here:
        ayuda.setBackground(Color.decode("#8D5925"));
        
    }//GEN-LAST:event_ayudaMouseEntered

    private void ayudaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ayudaMouseExited
        // TODO add your handling code here:
        ayuda.setBackground(Color.decode("#543516"));
        
    }//GEN-LAST:event_ayudaMouseExited

    private void jugar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugar1ActionPerformed
        // TODO add your handling code here:
        new ManejoDeMenus().displayJFrame(new Armas(), this);
        
    }//GEN-LAST:event_jugar1ActionPerformed

    private void jugar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugar1MouseEntered
        // TODO add your handling code here:
        jugar1.setBackground(Color.decode("#8D5925"));
        
    }//GEN-LAST:event_jugar1MouseEntered

    private void jugar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jugar1MouseExited
        // TODO add your handling code here:
        jugar1.setBackground(Color.decode("#543516"));
        
    }//GEN-LAST:event_jugar1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ayuda;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton jugar1;
    private javax.swing.JButton salir;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
