/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forgergame;

/**
 *
 * @author samuelzun
 */
public class GripPanel extends javax.swing.JPanel {

    /**
     * Creates new form GripPanel
     */
    public GripPanel(Grip grp, int id, Forjar grandparent) {
        initComponents();
        nameLb.setText(grp.getName());
        dmgLb.setText(grp.dmgstatString());
        spdLb.setText(grp.spdstatString());
        defLb.setText(grp.defstatString());
        wpnid = id;
        forjar = grandparent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLb = new javax.swing.JLabel();
        dmgLb = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        spdLb = new javax.swing.JLabel();
        defLb = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));

        nameLb.setBackground(new java.awt.Color(0, 0, 0));
        nameLb.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        nameLb.setForeground(new java.awt.Color(0, 0, 0));
        nameLb.setText("Name");

        dmgLb.setBackground(new java.awt.Color(0, 0, 0));
        dmgLb.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        dmgLb.setForeground(new java.awt.Color(0, 0, 0));
        dmgLb.setText("DMG");

        icon.setBackground(new java.awt.Color(0, 0, 0));
        icon.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        icon.setForeground(new java.awt.Color(0, 0, 0));
        icon.setText("*icon*");

        spdLb.setBackground(new java.awt.Color(0, 0, 0));
        spdLb.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        spdLb.setForeground(new java.awt.Color(0, 0, 0));
        spdLb.setText("SPD");

        defLb.setBackground(new java.awt.Color(0, 0, 0));
        defLb.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        defLb.setForeground(new java.awt.Color(0, 0, 0));
        defLb.setText("DEF");

        jButton1.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        jButton1.setText("Usar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(icon)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dmgLb)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(defLb)
                                    .addComponent(spdLb))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nameLb))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(icon)))
                .addGap(22, 22, 22)
                .addComponent(dmgLb)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spdLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(defLb)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        forjar.agarre = Data.mangos.get(wpnid);
        forjar.jLabel7.setText("Usando: "+Data.mangos.get(wpnid).getName());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private int wpnid;
    private Forjar forjar;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel defLb;
    private javax.swing.JLabel dmgLb;
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nameLb;
    private javax.swing.JLabel spdLb;
    // End of variables declaration//GEN-END:variables
}
