/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forgergame;

/**
 *
 * @author samuelzun
 */
public class WeaponPanel extends javax.swing.JPanel {

    /**
     * Creates new form WeaponPanel
     * @param wpn
     * @param id
     * @param prim
     * @param secun
     */
    public WeaponPanel(Weapon wpn, int id, javax.swing.JPanel prim, javax.swing.JPanel secun) {
        initComponents();
        nameLb.setText(wpn.getName());
        damageLb.setText("Daño: "+wpn.getDamage());
        speedLb.setText("Velocidad: "+wpn.getSpeed());
        defenseLb.setText("Defensa: "+wpn.getDefense());
        blockLb.setText("Bloqueo: "+wpn.getBlock()+"%");
        wpnid = id;
        primLb = prim;
        secunLb = secun;
        jButton2.setVisible(false);
    }
    
    public WeaponPanel(Weapon wpn, int id, int sl, javax.swing.JPanel parentsl) {
        initComponents();
        nameLb.setText(wpn.getName());
        damageLb.setText("Daño: "+wpn.getDamage());
        speedLb.setText("Velocidad: "+wpn.getSpeed());
        defenseLb.setText("Defensa: "+wpn.getDefense());
        blockLb.setText("Bloqueo: "+wpn.getBlock()+"%");
        wpnid = id;
        slot = sl;
        parentSlot = parentsl;
        jButton1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLb = new javax.swing.JLabel();
        damageLb = new javax.swing.JLabel();
        speedLb = new javax.swing.JLabel();
        defenseLb = new javax.swing.JLabel();
        blockLb = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 153));
        setForeground(new java.awt.Color(255, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameLb.setFont(new java.awt.Font("Papyrus", 0, 18)); // NOI18N
        nameLb.setForeground(new java.awt.Color(0, 0, 0));
        nameLb.setText("Name");
        add(nameLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, -1, -1));

        damageLb.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        damageLb.setForeground(new java.awt.Color(0, 0, 0));
        damageLb.setText("Daño");
        add(damageLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 55, -1, -1));

        speedLb.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        speedLb.setForeground(new java.awt.Color(0, 0, 0));
        speedLb.setText("Velocidad");
        add(speedLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, -1, -1));

        defenseLb.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        defenseLb.setForeground(new java.awt.Color(0, 0, 0));
        defenseLb.setText("Defensa");
        add(defenseLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 109, -1, -1));

        blockLb.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        blockLb.setForeground(new java.awt.Color(0, 0, 0));
        blockLb.setText("Bloqueo");
        add(blockLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 136, -1, -1));

        jLabel6.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("*icono*");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 82, -1, -1));

        jLabel7.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("++Encantamiento");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 163, -1, -1));

        jButton1.setBackground(new java.awt.Color(63, 41, 19));
        jButton1.setFont(new java.awt.Font("Papyrus", 0, 13)); // NOI18N
        jButton1.setText("USAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 6, -1, -1));

        jButton2.setBackground(new java.awt.Color(63, 41, 19));
        jButton2.setFont(new java.awt.Font("Papyrus", 0, 10)); // NOI18N
        jButton2.setText("REMOVER");
        jButton2.setActionCommand("REMOVER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        for (int w = 0; w < Data.equipado.length; w++) {
            if (Data.equipado[w] == null) {
                System.out.println(Data.equipado[w]);
                
                if (w == 0) {
                    if (Data.equipado[1] != null) {
                        if (Data.armas.get(wpnid).equals(Data.equipado[1])) {
                            break;
                        }
                    }
                    MetodosGUI.mostrarPanel(new WeaponPanel(Data.armas.get(wpnid), wpnid, w, primLb), primLb);
                } else if (w == 1) {
                    if (Data.equipado[0] != null) {
                        if (Data.armas.get(wpnid).equals(Data.equipado[0])) {
                            break;
                        }
                    }
                    
                    MetodosGUI.mostrarPanel(new WeaponPanel(Data.armas.get(wpnid), wpnid, w, secunLb), secunLb);
                }
                
                Data.equipado[w] = Data.armas.get(wpnid);
                
                break;
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.out.println(slot);
        Data.equipado[slot] = null;
        parentSlot.removeAll();
        parentSlot.revalidate();
        parentSlot.repaint();
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private int slot = -1;
    private int wpnid;
    private javax.swing.JPanel primLb;
    private javax.swing.JPanel secunLb;
    private javax.swing.JPanel parentSlot;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blockLb;
    private javax.swing.JLabel damageLb;
    private javax.swing.JLabel defenseLb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel nameLb;
    private javax.swing.JLabel speedLb;
    // End of variables declaration//GEN-END:variables
}
